---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver_config:
      use_sudo: false
      privileged: true      

suites:
  - name: default
    run_list:
      - recipe[lampstack::default]
    attributes:
