name 'lampstack'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures lampstack'
long_description 'Installs/Configures lampstack'
version '0.1.0'
